// KACHERI BACKEND/src/store/jaalProofs.ts
// JAAL Proofs: Store for cryptographic proof packets
//
// Tables: jaal_proofs
// See: Docs/Roadmap/beyle-platform-shell-work-scope.md - Slice S5

import { db } from "../db";

/* ---------- Types ---------- */

// Domain type (camelCase, for API) — matches frontend JaalProof interface
export interface JaalProof {
  id: string;
  sessionId: string | null;
  workspaceId: string;
  userId: string;
  kind: string;
  hash: string;
  payload: Record<string, unknown>;
  createdAt: string;  // ISO string
}

// Row type (snake_case, matches DB)
interface ProofRow {
  id: string;
  session_id: string | null;
  workspace_id: string;
  user_id: string;
  kind: string;
  hash: string;
  payload_json: string;
  created_at: number;
}

export interface CreateJaalProofInput {
  id: string;              // crypto.randomUUID() — generated by proofService
  sessionId?: string | null;
  workspaceId: string;
  userId: string;
  kind: string;
  hash: string;
  payload: Record<string, unknown>;
}

/* ---------- Row to Domain Converter ---------- */

function rowToProof(row: ProofRow): JaalProof {
  let payload: Record<string, unknown> = {};
  try {
    payload = JSON.parse(row.payload_json);
  } catch {
    payload = {};
  }

  return {
    id: row.id,
    sessionId: row.session_id,
    workspaceId: row.workspace_id,
    userId: row.user_id,
    kind: row.kind,
    hash: row.hash,
    payload,
    createdAt: new Date(row.created_at).toISOString(),
  };
}

/* ---------- CRUD Operations ---------- */

/** Create a new proof record */
async function create(input: CreateJaalProofInput): Promise<JaalProof> {
  const now = Date.now();
  const payloadJson = JSON.stringify(input.payload);

  try {
    await db.run(
      `INSERT INTO jaal_proofs (
        id, session_id, workspace_id, user_id,
        kind, hash, payload_json, created_at
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        input.id,
        input.sessionId ?? null,
        input.workspaceId,
        input.userId,
        input.kind,
        input.hash,
        payloadJson,
        now,
      ]
    );

    return (await getById(input.id))!;
  } catch (err) {
    console.error("[jaalProofs] Failed to create proof:", err);
    throw err;
  }
}

/** Get proof by ID */
async function getById(id: string): Promise<JaalProof | null> {
  try {
    const row = await db.queryOne<ProofRow>(
      `SELECT * FROM jaal_proofs WHERE id = ?`,
      [id]
    );
    return row ? rowToProof(row) : null;
  } catch (err) {
    console.error("[jaalProofs] Failed to get proof by id:", err);
    return null;
  }
}

/** List proofs for a workspace with optional filters */
async function listByWorkspace(
  workspaceId: string,
  opts?: {
    sessionId?: string;
    kind?: string;
    limit?: number;
  }
): Promise<JaalProof[]> {
  try {
    let query = `SELECT * FROM jaal_proofs WHERE workspace_id = ?`;
    const params: unknown[] = [workspaceId];

    if (opts?.sessionId) {
      query += ` AND session_id = ?`;
      params.push(opts.sessionId);
    }

    if (opts?.kind) {
      query += ` AND kind = ?`;
      params.push(opts.kind);
    }

    query += ` ORDER BY created_at DESC`;

    const limit = opts?.limit ?? 100;
    query += ` LIMIT ?`;
    params.push(limit);

    const rows = await db.queryAll<ProofRow>(query, params);
    return rows.map(rowToProof);
  } catch (err) {
    console.error("[jaalProofs] Failed to list proofs:", err);
    return [];
  }
}

/** List proofs linked to a specific session */
async function listBySession(sessionId: string): Promise<JaalProof[]> {
  try {
    const rows = await db.queryAll<ProofRow>(
      `SELECT * FROM jaal_proofs WHERE session_id = ? ORDER BY created_at DESC`,
      [sessionId]
    );
    return rows.map(rowToProof);
  } catch (err) {
    console.error("[jaalProofs] Failed to list proofs by session:", err);
    return [];
  }
}

/** Count proofs in a session */
async function countBySession(sessionId: string): Promise<number> {
  try {
    const row = await db.queryOne<{ count: number }>(
      `SELECT COUNT(*) as count FROM jaal_proofs WHERE session_id = ?`,
      [sessionId]
    );
    return row?.count ?? 0;
  } catch (err) {
    console.error("[jaalProofs] Failed to count proofs by session:", err);
    return 0;
  }
}

/* ---------- Export ---------- */

export const JaalProofStore = {
  create,
  getById,
  listByWorkspace,
  listBySession,
  countBySession,
};
